In [6]:
with open('One.txt') as mytext:
    words_one = mytext.read().lower().split()
    uni_words_one = set(words_one)

In [8]:
uni_words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [9]:
with open('Two.txt') as mytext:
    words_two = mytext.read().lower().split()
    uni_words_two = set(words_two)

In [10]:
uni_words_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [11]:
len(uni_words_one)

12

In [12]:
len(uni_words_two)

12

In [13]:
all_uni_words =set()
all_uni_words.update(uni_words_two)

In [15]:
all_uni_words.update(uni_words_one)

In [40]:
all_uni_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [106]:
full_vocab = dict()
i =0
for word in all_uni_words:
    full_vocab[word] = i
    i = i+1

In [108]:
set1 = {1,2,3,4}

In [19]:
full_vocab

{'about': 0,
 'is': 1,
 'fun': 2,
 'popular': 3,
 'furry': 4,
 'our': 5,
 'this': 6,
 'waves': 7,
 'sport': 8,
 'animals': 9,
 'story': 10,
 'canine': 11,
 'a': 12,
 'catching': 13,
 'are': 14,
 'pets': 15,
 'dogs': 16,
 'surfing': 17,
 'water': 18}

In [111]:
for word in full_vocab:
    print(word)

about
is
fun
popular
furry
our
this
waves
sport
animals
story
canine
a
catching
are
pets
dogs
surfing
water


In [89]:
one_freq = [0]*len(full_vocab)

In [90]:
two_freq = [0]*len(full_vocab)

In [91]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [92]:
two_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [93]:
all_words = ['']*len(full_vocab)

In [94]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [105]:
for word in full_vocab:
    word_ind = full_vocab[word]
    print(word_ind)
    all_words[word_ind] = word    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [96]:
all_words

['about',
 'is',
 'fun',
 'popular',
 'furry',
 'our',
 'this',
 'waves',
 'sport',
 'animals',
 'story',
 'canine',
 'a',
 'catching',
 'are',
 'pets',
 'dogs',
 'surfing',
 'water']

In [112]:
with open('One.txt') as f:
    one_text = f.read().lower().split()
    
for word in one_text:
    word_ind = full_vocab[word]
    one_freq[word_ind]+=1

In [98]:
one_freq

[1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 2, 0, 0]

In [99]:
with open('Two.txt') as f:
    two_text = f.read().lower().split()
    
for word in two_text:
    word_ind = full_vocab[word]
    two_freq[word_ind]+=1

In [102]:
two_freq

[1, 3, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 2, 1]

In [103]:
import pandas as pd

In [104]:
pd.DataFrame(data=[one_freq,two_freq],columns=all_words)

about  is  fun  popular  furry  our  this  waves  sport  animals  story  \
0      1   1    0        0      1    1     1      0      0        1      1   
1      1   3    1        1      0    0     1      1      1        0      1   

   canine  a  catching  are  pets  dogs  surfing  water  
0       1  1         0    1     1     2        0      0  
1       0  1         1    0     0     0        2      1

# Scikit-Learn's Text Feature Extraction Options¶

In [139]:
text = ['This is a line',
           "This is another line",
       "Completely different line"]

# CountVectorizer

In [140]:
from sklearn.feature_extraction.text import TfidfTransformer,TfidfVectorizer,CountVectorizer

In [153]:
cv = CountVectorizer()

In [154]:
cv.fit_transform(text)

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [155]:
sparse_mat = cv.fit_transform(text)

In [156]:
sparse_mat.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [157]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [158]:
cv1 = CountVectorizer(stop_words='english')

In [159]:
cv1.fit_transform(text).todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [160]:
cv1.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

In [149]:
tfidf_transformer = TfidfTransformer()

In [161]:
cv2 = CountVectorizer()

In [165]:
counts2 = cv2.fit_transform(text)

In [166]:
counts2.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [167]:
cv2.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [171]:
tfidf = tfidf_transformer.fit_transform(counts2)

In [172]:
tfidf.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

# TfIdfVectorizer
Does both above in a single step!

In [173]:
tfidf = TfidfVectorizer()

In [174]:
new = tfidf.fit_transform(text)

In [175]:
new.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])